import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import { Lato, Nunito } from "next/font/google";
import "./globals.css";
import 'antd/dist/reset.css';

const geistSans = Geist({
  subsets: ["latin"],
  display: 'swap',
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: 'swap',
});

const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
});

const lato = Lato({
  weight: ['400', '700'],
  subsets: ["latin"],
  display: 'swap',
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.className} ${geistMono.className} ${inter.className} ${lato.className} ${nunito.variable}`}>
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
